import { useCallback } from 'react';

export function useExport() {
  // ─── Share to WhatsApp ────────────────────────────────────────────────────
  const shareToWhatsApp = useCallback((text) => {
    const encoded = encodeURIComponent(text);
    window.open(`https://api.whatsapp.com/send?text=${encoded}`, '_blank');
  }, []);

  // ─── Copy text to clipboard ──────────────────────────────────────────────
  const copyText = useCallback(async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      // Fallback
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.left = '-9999px';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      return true;
    }
  }, []);

  // ─── Export as PDF via browser print ──────────────────────────────────────
  const exportAsPDF = useCallback((content, title = 'KanoonSaathi') => {
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: Georgia, serif; padding: 40px; color: #1a1a1a; max-width: 700px; margin: 0 auto; line-height: 1.7; }
          h1 { color: #FF6B00; border-bottom: 2px solid #FF6B00; padding-bottom: 8px; }
          h2 { color: #333; margin-top: 20px; }
          strong { color: #C0392B; }
          .section-head { color: #FF6B00; font-weight: 700; margin-top: 16px; font-size: 14px; border-bottom: 1px solid #ddd; padding-bottom: 3px; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #888; text-align: center; }
          pre { white-space: pre-wrap; word-wrap: break-word; background: #f4f4f4; padding: 12px; border-radius: 6px; font-size: 13px; }
        </style>
      </head>
      <body>
        <h1>⚖️ ${title}</h1>
        <div>${content.replace(/\n/g, '<br>')}</div>
        <div class="footer">Generated by KanoonSaathi — India's AI Legal Companion<br>⚠️ For informational purposes only. Consult DLSA for formal legal advice.</div>
      </body>
      </html>
    `);
    win.document.close();
    setTimeout(() => { win.print(); }, 500);
  }, []);

  // ─── Download as text file ────────────────────────────────────────────────
  const downloadAsText = useCallback((content, filename = 'kanoonsaathi.txt') => {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }, []);

  // ─── Native Share API (mobile) ────────────────────────────────────────────
  const nativeShare = useCallback(async (text, title = 'KanoonSaathi Legal Info') => {
    if (navigator.share) {
      try {
        await navigator.share({ title, text });
        return true;
      } catch { return false; }
    }
    return false;
  }, []);

  return { shareToWhatsApp, copyText, exportAsPDF, downloadAsText, nativeShare };
}
