import { useState, useRef, useEffect } from 'react';
import NavBar from '../components/NavBar';
import { QUICK_Q } from '../data/index';
import { LANGUAGES, getT } from '../data/languages';
import { SYSTEM_PROMPT } from '../data/systemPrompt';

export default function ChatPage({ loggedIn, user, lang, theme, fontSize, setTheme, setFontSize, onLangPick, onLogin, onSignup, onLogout, onHome, onProfile, onAdmin, speech, initialQuery, chatHistory }) {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [autoSpeak, setAutoSpeak] = useState(true);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [activeConvId, setActiveConvId] = useState(null);
  const endRef = useRef(null);
  const hasInitRef = useRef(false);

  const t = getT(lang);
  const activeLang = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];
  const { listening, speaking, transcript, micError, micPerm, hasStt, hasTts, supported, startListening, stopListening, speak, stopSpeaking, clearError } = speech;

  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);

  // Handle initial query from homepage
  useEffect(() => {
    if (initialQuery && !hasInitRef.current) {
      hasInitRef.current = true;
      ask(initialQuery, true);
    }
  }, [initialQuery]);

  // Auto-save conversation when messages change
  useEffect(() => {
    if (!chatHistory || messages.length < 2) return;
    if (activeConvId) {
      chatHistory.updateConversation(activeConvId, messages);
    }
  }, [messages]);

  const ask = async (text, fresh = false) => {
    const userText = (text || input).trim();
    if (!userText) return;
    setInput('');
    const base = fresh ? [] : messages;
    const msgs = [...base, { role: 'user', content: userText }];
    setMessages(msgs);
    setLoading(true);

    const langName = activeLang?.name || 'English';
    const langSuffix = lang !== 'en'
      ? `\n\nIMPORTANT: Respond entirely in ${langName} (${activeLang?.native}). Keep law section numbers in their original form. Do NOT respond in English.`
      : '';

    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: msgs,
          system: SYSTEM_PROMPT + langSuffix,
          language: lang,
        }),
      });

      const data = await res.json();

      if (data.error && !data.reply) {
        const errMsgs = [...msgs, { role: 'assistant', content: `⚠️ ${data.error}` }];
        setMessages(errMsgs);
      } else {
        const reply = data.reply || '⚠️ Unexpected server response. Please try again.';
        const fullMsgs = [...msgs, { role: 'assistant', content: reply }];
        setMessages(fullMsgs);
        if (autoSpeak) {
           try {
             const pd = JSON.parse(reply);
             speak(`${pd.legalPosition} ${pd.practicalSteps?.join('. ') || ''}`);
           } catch {
             speak(reply);
           }
        }

        // Save to chat history
        if (chatHistory) {
          if (activeConvId) {
            chatHistory.updateConversation(activeConvId, fullMsgs);
          } else {
            const newId = chatHistory.saveConversation(fullMsgs);
            setActiveConvId(newId);
          }
        }
      }
    } catch (err) {
      const msg = err?.message?.includes('Failed to fetch')
        ? '⚠️ Cannot reach server. Please check if the backend is running.'
        : `⚠️ Connection error: ${err?.message || 'unknown'}. Please try again.`;
      setMessages(prev => [...prev, { role: 'assistant', content: msg }]);
    }

    setLoading(false);
  };

  const formatForExport = (content) => {
    try {
      const data = JSON.parse(content);
      return `⚖️ Legal Position: ${data.legalPosition}\n\n📖 Law: ${data.relevantLaw?.bns || ''} ${data.relevantLaw?.ipc ? `(IPC: ${data.relevantLaw.ipc})` : ''}\n\n📋 Practical Steps:\n${data.practicalSteps?.map(s => `- ${s}`).join('\n')}\n\n👮 Remedies:\n${data.remedies?.map(r => `- ${r}`).join('\n')}\n\n⚠️ ${data.caveat || ''}`;
    } catch {
      return content;
    }
  };

  const copyLast = () => {
    const last = [...messages].reverse().find(m => m.role === 'assistant');
    if (last) { navigator.clipboard?.writeText(formatForExport(last.content)); setCopied(true); setTimeout(() => setCopied(false), 2000); }
  };

  const shareWhatsApp = () => {
    const last = [...messages].reverse().find(m => m.role === 'assistant');
    if (last) {
      const text = encodeURIComponent(`⚖️ KanoonSaathi Legal Info:\n\n${formatForExport(last.content).slice(0, 2000)}\n\n— Generated by KanoonSaathi`);
      window.open(`https://api.whatsapp.com/send?text=${text}`, '_blank');
    }
  };

  const exportPDF = () => {
    const last = [...messages].reverse().find(m => m.role === 'assistant');
    if (!last) return;
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(`<!DOCTYPE html><html><head><title>KanoonSaathi Legal Advice</title><style>body{font-family:Georgia,serif;padding:40px;max-width:700px;margin:0 auto;line-height:1.7;color:#1a1a1a}h1{color:#FF6B00;border-bottom:2px solid #FF6B00;padding-bottom:8px}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #ddd;font-size:11px;color:#888;text-align:center}</style></head><body><h1>⚖️ KanoonSaathi Legal Advice</h1><pre style="white-space:pre-wrap;font-family:Georgia,serif;font-size:14px">${formatForExport(last.content)}</pre><div class="footer">Generated by KanoonSaathi — India's AI Legal Companion<br>⚠️ For informational purposes only. Consult a licensed advocate or DLSA for formal legal advice.</div></body></html>`);
    w.document.close();
    setTimeout(() => w.print(), 500);
  };

  const loadConversation = (conv) => {
    setMessages(conv.messages);
    setActiveConvId(conv.id);
    setSidebarOpen(false);
    hasInitRef.current = true;
  };

  const newConversation = () => {
    setMessages([]);
    setActiveConvId(null);
    hasInitRef.current = true;
    setSidebarOpen(false);
  };

  const renderStructuredMessage = (content) => {
    let data;
    try {
      data = JSON.parse(content);
    } catch (e) {
      // Fallback for non-JSON or older messages
      return content.split('\n').map((line, i) => {
        const isH = ['⚖️','📖','✅','🔨','💡','📞','⚠️'].some(e => line.startsWith(e));
        if (isH) return <div key={i} style={{ marginTop:16,marginBottom:5,fontWeight:700,fontSize:13,color:'#FF9500',borderBottom:'1px solid rgba(255,149,0,0.15)',paddingBottom:3 }}>{line}</div>;
        const bold = line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
        return <div key={i} dangerouslySetInnerHTML={{ __html: bold || '&nbsp;' }} style={{ marginBottom:2,fontSize:14,lineHeight:1.65 }} />;
      });
    }

    if (!data.legalPosition) return <div>{content}</div>;

    const { confidenceScore, legalPosition, relevantLaw, practicalSteps, remedies, caveat } = data;
    const isHigh = confidenceScore >= 70;
    const isMed = confidenceScore >= 40 && confidenceScore < 70;
    const isLow = confidenceScore < 40;

    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', animation: 'fadeIn 0.3s ease' }}>
        {/* Confidence Badge */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <div style={{
            padding: '4px 8px', borderRadius: '4px', fontSize: '10px', fontWeight: 'bold', textTransform: 'uppercase',
            backgroundColor: isHigh ? 'rgba(76, 175, 80, 0.15)' : isMed ? 'rgba(255, 149, 0, 0.15)' : 'rgba(231, 76, 60, 0.15)',
            color: isHigh ? '#4CAF50' : isMed ? '#FF9500' : '#E74C3C', border: `1px solid ${isHigh ? 'rgba(76, 175, 80, 0.3)' : isMed ? 'rgba(255, 149, 0, 0.3)' : 'rgba(231, 76, 60, 0.3)'}`
          }}>
            {isHigh ? '🟢 High Confidence' : isMed ? '🟡 Medium Confidence' : '🔴 Low Confidence'}
          </div>
          <span style={{ fontSize: '11px', color: 'rgba(240,237,232,0.4)' }}>AI Match Score: {confidenceScore}/100</span>
        </div>

        {/* Legal Position */}
        <div>
          <strong style={{ color: '#FF9500', fontSize: '13px' }}>⚖️ Legal Position</strong>
          <div style={{ fontSize: '14px', marginTop: '4px', lineHeight: '1.65' }}>{legalPosition}</div>
        </div>

        {/* Relevant Law (Hide specific sections if Low/Medium confidence to prevent bad advice) */}
        {(isHigh) && relevantLaw && (relevantLaw.ipc || relevantLaw.bns) && (
          <div style={{ padding: '10px 12px', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '8px', borderLeft: '3px solid #FF6B00' }}>
            <strong style={{ color: '#FF6B00', fontSize: '12px', display: 'block', marginBottom: '4px' }}>📖 Applicable Law</strong>
            {relevantLaw.bns && <div style={{ fontSize: '13px' }}><strong>BNS:</strong> {relevantLaw.bns}</div>}
            {relevantLaw.ipc && <div style={{ fontSize: '12px', color: 'rgba(240,237,232,0.5)' }}>Historical IPC: {relevantLaw.ipc}</div>}
            {relevantLaw.framework && <div style={{ fontSize: '11px', color: 'rgba(240,237,232,0.3)', marginTop: '4px' }}>{relevantLaw.framework}</div>}
          </div>
        )}

        {/* Practical Steps */}
        {practicalSteps && practicalSteps.length > 0 && (
          <div>
            <strong style={{ color: '#4CAF50', fontSize: '13px' }}>📋 Practical Steps</strong>
            <ol style={{ paddingLeft: '22px', margin: '4px 0 0 0', fontSize: '14px', lineHeight: '1.6' }}>
              {practicalSteps.map((step, i) => <li key={i}>{step}</li>)}
            </ol>
          </div>
        )}

        {/* Remedies */}
        {remedies && remedies.length > 0 && (
          <div>
            <strong style={{ color: '#E74C3C', fontSize: '13px' }}>👮 Remedies / Escalation</strong>
            <ul style={{ paddingLeft: '22px', margin: '4px 0 0 0', fontSize: '14px', lineHeight: '1.6' }}>
              {remedies.map((rem, i) => <li key={i}>{rem}</li>)}
            </ul>
          </div>
        )}

        {/* Caveats / Warnings */}
        {caveat && (
          <div style={{ marginTop: '4px', padding: '8px 10px', backgroundColor: 'rgba(255, 149, 0, 0.05)', borderRadius: '6px', fontSize: '12px', color: 'rgba(240,237,232,0.8)' }}>
            <strong>⚠️ Note:</strong> {caveat}
          </div>
        )}
        
        {isLow && (
          <div style={{ marginTop: '4px', padding: '8px 10px', backgroundColor: 'rgba(231, 76, 60, 0.08)', borderRadius: '6px', fontSize: '12px', color: '#E74C3C', border: '1px solid rgba(231, 76, 60, 0.2)' }}>
            <strong>⚠️ Warning:</strong> Due to low confidence in matching specific laws, this is general legal information. For precise actions, consult an advocate.
          </div>
        )}
      </div>
    );
  };


  const conversations = chatHistory?.conversations || [];

  return (
    <div className="chat-container" style={{ background:'#07070F',color:'#F0EDE8',fontFamily:'Georgia,serif' }}>
      <NavBar loggedIn={loggedIn} user={user} onLogin={onLogin} onSignup={onSignup} lang={lang} theme={theme} fontSize={fontSize} setTheme={setTheme} setFontSize={setFontSize} onLangPick={onLangPick} onLogout={onLogout} onProfile={onProfile} onHome={onHome} onAdmin={onAdmin} back={onHome} backLabel="← Home" />

      {/* Chat History Sidebar */}
      {sidebarOpen && (
        <div style={{ position:'fixed',inset:0,zIndex:100,display:'flex' }}>
          <div onClick={() => setSidebarOpen(false)} style={{ flex:1,background:'rgba(0,0,0,0.5)' }} />
          <div style={{ width:320,maxWidth:'85vw',background:'#0E0E1A',borderLeft:'1px solid rgba(255,107,0,0.15)',padding:'20px 16px',overflowY:'auto',animation:'slideIn 0.2s ease' }}>
            <div style={{ display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:18 }}>
              <div style={{ fontSize:15,fontWeight:700 }}>💬 Chat History</div>
              <button onClick={() => setSidebarOpen(false)} style={{ background:'none',border:'none',color:'rgba(240,237,232,0.4)',cursor:'pointer',fontSize:18 }}>✕</button>
            </div>

            <button onClick={newConversation} className="btn btn-primary" style={{ width:'100%',marginBottom:16,padding:10,borderRadius:8,fontSize:12 }}>
              ✨ New Conversation
            </button>

            {conversations.length === 0 ? (
              <div style={{ textAlign:'center',padding:'24px 0',color:'rgba(240,237,232,0.3)',fontSize:12 }}>
                <div style={{ fontSize:32,marginBottom:8 }}>💬</div>
                No conversations yet.<br/>Start chatting to save history.
              </div>
            ) : (
              <>
                {conversations.map((conv) => (
                  <div key={conv.id} onClick={() => loadConversation(conv)}
                    style={{ padding:'10px 12px',borderRadius:10,marginBottom:6,cursor:'pointer',border:`1px solid ${activeConvId === conv.id ? 'rgba(255,107,0,0.35)' : 'rgba(255,255,255,0.06)'}`,background: activeConvId === conv.id ? 'rgba(255,107,0,0.08)' : 'rgba(255,255,255,0.02)',transition:'all 0.15s' }}
                    onMouseEnter={e => { if (activeConvId !== conv.id) e.currentTarget.style.background = 'rgba(255,255,255,0.04)'; }}
                    onMouseLeave={e => { if (activeConvId !== conv.id) e.currentTarget.style.background = 'rgba(255,255,255,0.02)'; }}>
                    <div style={{ fontSize:12,fontWeight:600,color:'rgba(240,237,232,0.8)',marginBottom:3,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap' }}>{conv.title}</div>
                    <div style={{ display:'flex',alignItems:'center',justifyContent:'space-between' }}>
                      <span style={{ fontSize:10,color:'rgba(240,237,232,0.25)' }}>{conv.messageCount} msgs · {new Date(conv.updatedAt).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</span>
                      <button onClick={(e) => { e.stopPropagation(); chatHistory.deleteConversation(conv.id); if (activeConvId === conv.id) newConversation(); }}
                        style={{ background:'none',border:'none',color:'rgba(231,76,60,0.4)',cursor:'pointer',fontSize:12,padding:'2px 4px' }} title="Delete">🗑</button>
                    </div>
                  </div>
                ))}
                {conversations.length > 1 && (
                  <button onClick={chatHistory.clearAll} style={{ width:'100%',marginTop:8,padding:'7px',borderRadius:7,background:'rgba(231,76,60,0.06)',border:'1px solid rgba(231,76,60,0.18)',color:'rgba(231,76,60,0.5)',fontSize:10,cursor:'pointer',fontFamily:'inherit' }}>
                    🗑 Clear All History
                  </button>
                )}
              </>
            )}
          </div>
        </div>
      )}

      <div style={{ flex:1,display:'flex',flexDirection:'column',maxWidth:760,width:'100%',margin:'0 auto',minHeight:0 }}>
        {/* Header */}
        <div style={{ padding:'12px 20px 10px',borderBottom:'1px solid rgba(255,255,255,0.06)',display:'flex',alignItems:'center',justifyContent:'space-between',flexShrink:0 }}>
          <div>
            <div style={{ fontSize:15,fontWeight:700 }}>⚖️ Legal Query Assistant</div>
            <div style={{ fontSize:11,color:'rgba(240,237,232,0.35)' }}>Describe your problem in plain language — private & encrypted</div>
          </div>
          <div style={{ display:'flex',alignItems:'center',gap:8 }}>
            {chatHistory && (
              <button onClick={() => setSidebarOpen(true)} className="btn btn-ghost" style={{ fontSize:11,display:'flex',alignItems:'center',gap:4 }}>
                💬 History{conversations.length > 0 ? ` (${conversations.length})` : ''}
              </button>
            )}
            {messages.length > 0 && (
              <>
                <button onClick={copyLast} className="btn btn-ghost" style={{ fontSize:11 }}>
                  {copied ? '✅ Copied' : '📋 Copy'}
                </button>
                <button onClick={shareWhatsApp} className="btn btn-ghost" style={{ fontSize:11 }}>📱 Share</button>
                <button onClick={exportPDF} className="btn btn-ghost" style={{ fontSize:11 }}>📥 PDF</button>
              </>
            )}
            <div style={{ fontSize:10,color:'#4CAF50',display:'flex',alignItems:'center',gap:3 }}>
              <div style={{ width:5,height:5,borderRadius:'50%',background:'#4CAF50',animation:'pulse 2s infinite' }} />
              Encrypted
            </div>
          </div>
        </div>

        {/* Messages */}
        <div className="chat-messages">
          {messages.length === 0 && (
            <div style={{ textAlign:'center',padding:'16px 0',animation:'fadeIn 0.5s ease' }}>
              <div style={{ fontSize:44,marginBottom:10,animation:'glow 3s infinite',display:'inline-block' }}>⚖️</div>
              <div style={{ fontSize:17,fontWeight:700,marginBottom:5 }}>{t.chatWelcome}</div>
              <div style={{ fontSize:13,color:'rgba(240,237,232,0.38)',marginBottom:12,lineHeight:1.7,direction:activeLang.dir }}>{t.chatSub}</div>
              {supported.stt && (
                <div style={{ display:'inline-flex',alignItems:'center',gap:9,padding:'10px 18px',borderRadius:20,background:'rgba(231,76,60,0.09)',border:'1px solid rgba(231,76,60,0.25)',marginBottom:16,animation:'glow 3s infinite' }}>
                  <span style={{ fontSize:20 }}>🎙️</span>
                  <span style={{ fontSize:12,color:'rgba(240,237,232,0.75)' }}>Can't type? <strong style={{ color:'#E74C3C' }}>Tap the red mic button</strong> below and speak your problem</span>
                </div>
              )}
              <div style={{ fontSize:11,color:'rgba(240,237,232,0.25)',marginBottom:10 }}>Try a quick scenario:</div>
              <div style={{ display:'flex',flexWrap:'wrap',gap:7,justifyContent:'center' }}>
                {QUICK_Q.map((sc, i) => (
                  <button key={i} onClick={() => ask(sc.q, true)}
                    style={{ padding:'6px 11px',borderRadius:16,background:'rgba(255,107,0,0.07)',border:'1px solid rgba(255,107,0,0.18)',color:'#FF9500',fontSize:10,cursor:'pointer',fontFamily:'inherit',display:'flex',alignItems:'center',gap:4,animation:`fadeUp 0.3s ease ${i*0.04}s both` }}>
                    {sc.icon} {sc.q.length > 42 ? sc.q.slice(0, 42) + '…' : sc.q}
                  </button>
                ))}
              </div>

              {/* Show past conversations */}
              {conversations.length > 0 && (
                <div style={{ marginTop:20,paddingTop:16,borderTop:'1px solid rgba(255,255,255,0.06)' }}>
                  <div style={{ fontSize:11,color:'rgba(240,237,232,0.25)',marginBottom:8 }}>Recent conversations:</div>
                  <div style={{ display:'flex',flexWrap:'wrap',gap:6,justifyContent:'center' }}>
                    {conversations.slice(0, 5).map((conv) => (
                      <button key={conv.id} onClick={() => loadConversation(conv)}
                        style={{ padding:'5px 10px',borderRadius:12,background:'rgba(255,255,255,0.03)',border:'1px solid rgba(255,255,255,0.08)',color:'rgba(240,237,232,0.55)',fontSize:10,cursor:'pointer',fontFamily:'inherit',maxWidth:180,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap' }}>
                        💬 {conv.title}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {messages.filter(m => !m._retry).map((m, i) => (
            <div key={`${m.role}-${i}`} className={m.role === 'user' ? 'chat-user-msg' : 'chat-ai-msg'}>
              {m.role === 'assistant' && (
                <div style={{ fontSize:10,color:'#FF9500',fontWeight:700,marginBottom:7,display:'flex',alignItems:'center',justifyContent:'space-between' }}>
                  <span>⚖️ KanoonSaathi</span>
                  <div style={{ display:'flex',alignItems:'center',gap:6 }}>
                    {supported.tts && (
                      <button onClick={() => speaking ? stopSpeaking() : speak(m.content)}
                        style={{ background:'none',border:'none',cursor:'pointer',fontSize:13,padding:'0 2px',opacity:0.65 }}
                        title="Read aloud">
                        {speaking ? '⏹' : '🔊'}
                      </button>
                    )}
                    <button onClick={() => { navigator.clipboard?.writeText(m.content); }}
                      style={{ background:'none',border:'none',cursor:'pointer',fontSize:11,padding:'0 2px',opacity:0.45,color:'#F0EDE8' }}
                      title="Copy this message">📋</button>
                    <button onClick={() => { const text = encodeURIComponent(`⚖️ KanoonSaathi:\n\n${m.content.slice(0,2000)}`); window.open(`https://api.whatsapp.com/send?text=${text}`, '_blank'); }}
                      style={{ background:'none',border:'none',cursor:'pointer',fontSize:11,padding:'0 2px',opacity:0.45,color:'#F0EDE8' }}
                      title="Share via WhatsApp">📱</button>
                  </div>
                </div>
              )}
              {m.role === 'assistant' ? renderStructuredMessage(m.content) : m.content}
            </div>
          ))}

          {loading && (
            <div className="chat-ai-msg">
              <div style={{ fontSize:10,color:'#FF9500',fontWeight:700,marginBottom:8 }}>⚖️ KanoonSaathi</div>
              <div style={{ display:'flex',gap:5,alignItems:'center' }}>
                {[0,1,2].map(j => <div key={j} style={{ width:7,height:7,borderRadius:'50%',background:'#FF6B00',animation:`pulse 1.2s ${j*0.2}s infinite` }} />)}
                <span style={{ fontSize:11,color:'rgba(240,237,232,0.33)',marginLeft:6 }}>Researching applicable laws…</span>
              </div>
            </div>
          )}
          <div ref={endRef} />
        </div>

        {/* Listening banner */}
        {listening && (
          <div style={{ margin:'0 20px 8px',padding:'11px 16px',background:'rgba(231,76,60,0.1)',border:'1px solid rgba(231,76,60,0.35)',borderRadius:10,display:'flex',alignItems:'center',gap:12,flexShrink:0,animation:'fadeIn 0.2s ease' }}>
            <div style={{ display:'flex',gap:3,alignItems:'flex-end',height:22 }}>
              {[0,1,2,3,4].map(i => <div key={i} style={{ width:3,borderRadius:3,background:'#E74C3C',animation:`wave 0.9s ${i*0.12}s ease-in-out infinite` }} />)}
            </div>
            <div style={{ flex:1 }}>
              <div style={{ fontSize:12,fontWeight:700,color:'#E74C3C' }}>🎙️ Listening… speak now</div>
              {transcript ? <div style={{ fontSize:11,color:'rgba(240,237,232,0.8)',marginTop:2 }}>"{transcript}"</div>
                : <div style={{ fontSize:11,color:'rgba(240,237,232,0.4)',marginTop:2 }}>Will send automatically when you stop speaking</div>}
            </div>
            <button className="btn" onClick={stopListening} style={{ background:'rgba(231,76,60,0.2)',border:'1px solid rgba(231,76,60,0.4)',color:'#E74C3C',fontSize:11 }}>Cancel</button>
          </div>
        )}

        {/* Mic error */}
        {micError && (
          <div style={{ margin:'0 20px 8px',padding:'11px 14px',background:'rgba(231,76,60,0.1)',border:'1px solid rgba(231,76,60,0.4)',borderRadius:10,display:'flex',alignItems:'flex-start',gap:10,flexShrink:0 }}>
            <span style={{ fontSize:16 }}>⚠️</span>
            <div style={{ flex:1,fontSize:12,color:'#E74C3C',lineHeight:1.55 }}>{micError}</div>
            <button onClick={clearError} style={{ background:'none',border:'none',color:'rgba(231,76,60,0.6)',cursor:'pointer',fontSize:16,padding:0 }}>✕</button>
          </div>
        )}

        {/* Speaking banner */}
        {speaking && (
          <div style={{ margin:'0 20px 8px',padding:'10px 16px',background:'rgba(76,175,80,0.08)',border:'1px solid rgba(76,175,80,0.25)',borderRadius:10,display:'flex',alignItems:'center',gap:10,flexShrink:0 }}>
            <div style={{ fontSize:16,animation:'speakPulse 1s infinite' }}>🔊</div>
            <div style={{ flex:1,fontSize:12,color:'#4CAF50' }}>Reading response aloud…</div>
            <button className="btn" onClick={stopSpeaking} style={{ background:'rgba(76,175,80,0.12)',border:'1px solid rgba(76,175,80,0.3)',color:'#4CAF50',fontSize:11 }}>Stop</button>
          </div>
        )}

        {/* Disclaimer Banner */}
        <div style={{ margin:'0 20px 8px',padding:'10px 14px',background:'rgba(255,149,0,0.08)',border:'1px solid rgba(255,149,0,0.25)',borderRadius:10,display:'flex',alignItems:'flex-start',gap:10,flexShrink:0 }}>
          <span style={{ fontSize:16 }}>⚠️</span>
          <div style={{ flex:1,fontSize:11,color:'rgba(240,237,232,0.7)',lineHeight:1.4 }}>
            <strong style={{ color:'#FF9500' }}>Not legal advice.</strong> KanoonSaathi is an AI assistant, not a lawyer. Information provided is for educational purposes. Consult a qualified advocate or DLSA for official legal counsel.
          </div>
        </div>

        {/* Input area */}
        <div className="chat-input-area">
          <button
            onClick={() => {
              if (listening) { stopListening(); }
              else { startListening((text) => { if (text?.trim()) ask(text.trim(), false); }); }
            }}
            title={listening ? 'Tap to cancel' : hasStt ? 'Tap to speak' : 'Voice not supported'}
            style={{
              width:48,height:48,borderRadius:12,border:'none',cursor:'pointer',
              display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:2,fontSize:20,flexShrink:0,
              background: listening ? '#E74C3C' : micPerm === 'denied' ? 'rgba(231,76,60,0.06)' : 'rgba(231,76,60,0.12)',
              color: listening ? '#fff' : micPerm === 'denied' ? 'rgba(231,76,60,0.4)' : '#E74C3C',
              transition:'all 0.2s',
              animation: listening ? 'micPulse 1.2s infinite' : 'none',
              boxShadow: listening ? '0 0 0 3px rgba(231,76,60,0.3)' : 'none',
            }}>
            <span>{listening ? '⏹' : '🎙️'}</span>
            <span style={{ fontSize:7,letterSpacing:'0.3px',opacity:0.75 }}>{listening ? 'STOP' : micPerm === 'denied' ? 'BLOCKED' : 'SPEAK'}</span>
          </button>

          <textarea
            className="input"
            style={{ flex:1,resize:'none',maxHeight:120,minHeight:48 }}
            value={input} onChange={e => setInput(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); ask(); } }}
            placeholder={listening ? '🎙️ Listening — speak now…' : hasStt ? `${t.chatPH} — or tap 🎙️ to speak` : t.chatPH}
            dir={activeLang.dir}
            rows={2}
          />

          {hasTts && (
            <button onClick={() => { setAutoSpeak(a => !a); if (speaking) stopSpeaking(); }}
              title={autoSpeak ? 'Voice ON — tap to mute' : 'Voice OFF — tap to enable'}
              style={{
                width:48,height:48,borderRadius:12,cursor:'pointer',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:2,fontSize:18,flexShrink:0,
                border:`1px solid ${autoSpeak ? 'rgba(76,175,80,0.4)' : 'rgba(255,255,255,0.1)'}`,
                background: autoSpeak ? 'rgba(76,175,80,0.12)' : 'rgba(255,255,255,0.03)',
                color: autoSpeak ? '#4CAF50' : 'rgba(240,237,232,0.3)',transition:'all 0.2s',
              }}>
              <span>{autoSpeak ? '🔊' : '🔇'}</span>
              <span style={{ fontSize:7,opacity:0.75 }}>{autoSpeak ? 'ON' : 'OFF'}</span>
            </button>
          )}

          <button onClick={() => ask()} disabled={loading} className="btn btn-primary" style={{ padding:'11px 18px',borderRadius:10,fontSize:13,opacity:loading?0.6:1 }}>
            {loading ? '…' : t.askAiBtn}
          </button>
        </div>
      </div>
    </div>
  );
}
